// build-sync.test.mjs — 守卫：site/_worker.js 必须与 worker-src/ 的当前内容一致。
//
// 为什么需要它（2026-09-11）：
//   p1-billing 里有一条断言长期"假绿" —— 源码早已改成 `success_url = .../upgrade.html?checkout=done`，
//   但测试读的是构建产物 site/_worker.js，产物没重建，断言就对着旧字符串一直通过。
//   直到手动重建产物才暴露。
//
//   那次的一半修复是把功能测试改成读 worker-src 源码；这个守卫补上另一半：
//   **产物本身也必须跟得上源码**，否则部署上去的就是旧逻辑 ——
//   而部署脚本 deploy.ps1 会自动构建，所以这个守卫拦的是"你以为测过了、其实测的是旧产物"。
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const BANNER = '// Generated by build-worker.mjs from worker-src/*.mjs — do not edit site/_worker.js by hand.';

test('site/_worker.js 与 worker-src 同步（改了源码必须 npm run build:worker）', async () => {
  const res = await build({
    entryPoints: [ROOT + 'worker-src/worker.mjs'],
    bundle: true,
    format: 'esm',
    target: 'es2022',
    platform: 'browser',
    write: false,
    banner: { js: BANNER },
  });
  const fresh = res.outputFiles[0].text;
  const onDisk = readFileSync(ROOT + 'site/_worker.js', 'utf8');

  assert.equal(
    onDisk,
    fresh,
    'site/_worker.js 落后于 worker-src。跑 `npm run build:worker` 重建后再跑测试 —— ' +
    '否则部署上去的会是旧逻辑，而测试这边看不出问题。'
  );
});
