import json,glob,os
ROOT=r'E:\Triumph\praxis-5001';BD=os.path.join(ROOT,'assets','batches')
fix={
('B31.json','5002-094'):{'question':'Which sentence contains clear onomatopoeia?','options':['The wind moved through the trees.','The bell was large.','The bell went ding-dong.','The cold felt bitter.'],'answer_index':2,'explanation':"'Ding-dong' imitates the sound of a bell and is therefore onomatopoeia. The other choices describe actions or qualities without reproducing a sound."},
('B86.json','5002-190'):{'question':'A student decodes grade-level text accurately and understands the vocabulary but cannot make inferences, summarize, or notice when meaning breaks down. Which skill is most likely weak?','options':['Reading speed','Decoding','Reading comprehension strategies: inferencing, synthesizing, and monitoring understanding','Letter recognition'],'answer_index':2,'explanation':'The evidence rules out basic decoding and vocabulary problems and points to weak higher-order comprehension strategies. Explicit instruction in inference, summarization, and comprehension monitoring directly targets the observed difficulties.'},
('B21.json','5003-046'):{'question':'For any two positive integers a and b, which relationship is true?','options':['There is no relationship between GCD and LCM','GCD(a,b) × LCM(a,b) = a × b','GCD is always larger than LCM','GCD(a,b) = LCM(a,b)'],'answer_index':1,'explanation':'For positive integers, the product of the greatest common divisor and least common multiple equals the product of the two integers. For 4 and 6, 2 × 12 = 4 × 6 = 24.'},
('B23.json','5003-058'):{'question':'Students measure the lengths of four ropes as 1.2 m, 95 cm, 1.05 m, and 110 cm. Which step best supports an accurate comparison?','options':['Compare the written digits without considering units','Convert all measurements to the same unit before ordering them','Round every measurement to the nearest meter','Count the strands in each rope'],'answer_index':1,'explanation':'Measurements must use a common unit before they can be compared reliably. Converting all lengths to centimeters or meters preserves their values; comparing raw digits or over-rounding can reverse the order.'},
('B69.json','5003-106'):{'difficulty':'medium','type':'concept','question':'A pattern begins 4, 7, 10, 13. Which rule describes the nth term?','options':['3n + 1','4n - 1','n + 3','4n + 3'],'answer_index':0,'explanation':'The sequence increases by 3 and begins with 4 when n = 1, so 3n + 1 generates 4, 7, 10, and 13. The other rules do not reproduce all four terms.'},
('B75.json','5003-116'):{'options':['The result depends on the number','Zero has no place value','n × 0 means n groups of zero, so the sum is zero','Zero changes every number to one'],'answer_index':2,'explanation':'Multiplication can represent equal groups: n × 0 is n groups containing zero objects. Adding zero n times gives zero, so the product is always zero.'},
('B81.json','5003-126'):{'options':['As x increases, y decreases—a decreasing linear relationship','The line rises from left to right','There is no relationship between x and y','The line is vertical'],'answer_index':0,'explanation':'A negative slope means y decreases at a constant rate as x increases. This is a decreasing linear relationship, not inverse variation, which usually has the form y = k/x.'},
('B91.json','5003-154'):{'difficulty':'medium','question':'A data set is 4, 6, 6, 7, and 22. Which measure best describes a typical value when the high outlier is considered?','options':['Median, because it is less affected by the outlier','Mean, because it is always one of the data values','Range, because it identifies the center','Mode, because it uses every value'],'answer_index':0,'explanation':'The median is 6 and is resistant to the unusually high value 22. The mean is pulled upward by the outlier, while range measures spread rather than center.'},
('B95.json','5003-162'):{'difficulty':'medium','question':'Which statement about rational and irrational numbers is true?','options':['Every decimal is irrational','A terminating or repeating decimal is rational','The square root of every whole number is rational','Irrational numbers can be written as ratios of integers'],'answer_index':1,'explanation':'A terminating or repeating decimal can be expressed as a fraction and is therefore rational. Irrational numbers have nonterminating, nonrepeating decimal expansions and cannot be written as ratios of integers.'},
('B19.json','5004-049'):{'question':'Which geographic tool is best suited for analyzing layers of population, roads, and land use together?','options':['A compass used only to find direction','A geographic information system (GIS)','A political speech','A chronological timeline'],'answer_index':1,'explanation':'GIS stores and overlays spatial data layers, allowing users to analyze relationships among population, transportation, and land use. A compass provides direction but cannot combine data layers.'},
('B39.json','5004-110'):{'question':'Which river carries the greatest average volume of water to the ocean?','options':['Nile','Yangtze','Mississippi','Amazon'],'answer_index':3,'explanation':'The Amazon River has by far the greatest average discharge of any river. This avoids the disputed question of whether the Nile or Amazon is longest under different measurement methods.'},
('B76.json','5004-194'):{'question':'How are migration and displacement related?','options':['Migration includes voluntary and forced movement; displacement specifically means people are forced from their homes','They are unrelated processes','Displacement is always voluntary','Migration occurs only across international borders'],'answer_index':0,'explanation':'Migration is a broad term for movement from one place to another and may be voluntary or forced. Displacement is a form of forced movement caused by conflict, disaster, persecution, or similar pressures.'},
('B94.json','5004-229'):{'question':'Students think the Bill of Rights restricts only the federal government. Which explanation best corrects the misconception?','options':['The Bill of Rights directly governs every private action','State governments may ignore the Bill of Rights','The Fourteenth Amendment has been used to apply most Bill of Rights protections to state governments','The Bill of Rights was repealed after the Civil War'],'answer_index':2,'explanation':'Through selective incorporation under the Fourteenth Amendment, courts have applied most Bill of Rights protections to state and local governments. These protections still generally concern government action, not ordinary private conduct.'},
('B68.json','5004-173'):{'question':'How should a teacher explain the limited political participation present at the nation’s founding?','options':['The Constitution itself created one uniform property requirement for all voters','Voting eligibility was largely controlled by states, many of which restricted participation by sex, race, property, or legal status','Every adult citizen could vote from the beginning','Political participation was unrelated to state law'],'answer_index':1,'explanation':'The original Constitution left most voter qualifications to the states. Many states restricted voting through property, sex, race, and status rules, while slavery also denied political rights to enslaved people.'},
('B84.json','5004-208'):{'options':['The President submits a budget request; Congress develops and passes spending legislation; the President signs or vetoes it','The President alone determines all federal spending','The Supreme Court writes the annual budget','State governments approve the federal budget'],'answer_index':0,'explanation':'The executive branch submits a budget request, but Congress exercises the power of the purse by enacting appropriations and other spending legislation. The President then signs or vetoes the legislation.'},
('B33.json','5004-095'):{'options':['Congress directly chooses the President in every election','Each state receives electors equal to its total representation in Congress; D.C. receives three, and electors cast presidential votes','The Vice President assigns electors after the election','The national popular-vote winner automatically receives every electoral vote'],'answer_index':1,'explanation':'A state’s electors equal its number of representatives plus two senators, and the Twenty-third Amendment gives D.C. three electors. This allocation reflects population through House seats but is not purely proportional because every state also has two Senate-based electors.'},
('B24.json','5004-064'):{'options':['A Senate tactic used to prolong debate or delay or prevent a vote','A constitutional amendment','A presidential veto','A procedure for ending debate immediately'],'answer_index':0,'explanation':'A filibuster is an effort in the Senate to prolong debate or delay or prevent a vote. For most legislation, invoking cloture generally requires three-fifths of the full Senate, usually 60 votes.'},
('B52.json','5004-153'):{'options':['A presidential veto','A formal type of ceremonial speech','A procedure used only in the House','A Senate tactic used to prolong debate or delay or prevent a vote'],'answer_index':3,'explanation':'A filibuster is a Senate strategy for prolonging debate or delaying or blocking a vote. It does not always require continuous floor speaking; cloture can limit debate under Senate rules.'},
('B94.json','5004-232'):{'options':['A court ruling','A method of counting ballots','A Senate tactic used to prolong debate or delay or prevent a vote','An executive order'],'answer_index':2,'explanation':'A filibuster is a Senate strategy for prolonging debate or delaying or blocking a vote. For most legislation, cloture generally requires 60 votes; different rules apply to some nominations and procedures.'},
('B24.json','5004-066'):{'question':'Which approach best evaluates the reliability of a historical source?','options':['Accept it whenever it was created during the event','Examine the author, purpose, context, and corroboration with other evidence','Prefer the source with the most dramatic language','Use only modern summaries'],'answer_index':1,'explanation':'A source is not automatically reliable merely because it is primary. Historians evaluate who created it, for what purpose, in what context, and whether other evidence corroborates its claims.'},
('B56.json','5004-156'):{'question':'What was the immediate trigger of World War I?','options':['The assassination of Archduke Franz Ferdinand and the crisis that followed','A single religious dispute','An international economic depression','A natural disaster in Europe'],'answer_index':0,'explanation':'The assassination in Sarajevo triggered the July Crisis and activation of alliance commitments. Militarism, imperial competition, nationalism, and alliances were important long-term causes rather than the single immediate trigger.'},
('B36.json','5004-103'):{'question':'Which innovation supplied mechanical power to many early factories and later transformed rail and steamship transportation?','options':['The printing press','The improved steam engine','The wheel','The magnetic compass'],'answer_index':1,'explanation':'Improved steam engines powered machinery independently of flowing water and later drove locomotives and steamships. The question specifies the role rather than claiming one invention was the only key innovation of industrialization.'},
('B7.json','5004-019'):{'question':'A sociologist compares how unemployment, housing policy, and policing patterns affect crime rates across many cities. Which level of analysis is being used?','options':['Biological determinism','Micro-level face-to-face interaction','Macro-level structural analysis','Individual psychology'],'answer_index':2,'explanation':'The study examines large-scale institutions and structural conditions across cities, which is macro-level analysis. Micro-level analysis would focus on direct interactions among individuals.'},
('B41.json','5004-120'):{'category':'United States History, Government, and Citizenship'},
('B8.json','5004-031'):{'category':'Geography, Anthropology, and Sociology'},
('B84.json','5004-213'):{'category':'World History and Economics'},
('B84.json','5004-216'):{'question':'Who was the longest-serving U.S. president?'},
('B17.json','5005-051'):{'question':'Which investigation best demonstrates osmosis?','options':['Observe identical potato strips before treatment only','Place equal potato strips in distilled water and salt solutions, then measure changes in mass','Count cells in a dry microscope slide','Compare ropes of different thickness'],'answer_index':1,'explanation':'Using equal potato strips, controlled solution volumes, and before-and-after mass measurements provides observable evidence of water movement across cell membranes. A comparison without treatment or measurement cannot demonstrate osmosis.'},
('B17.json','5005-056'):{'question':'Which kingdom is characterized mainly by multicellular organisms that carry out photosynthesis?','options':['Plantae','Animalia','Fungi','Archaea'],'answer_index':0,'explanation':'Members of Plantae are predominantly multicellular photosynthetic organisms. Some protists are also photosynthetic, so asking only which kingdom “includes” autotrophs would not have a unique answer.'},
('B25.json','5005-075'):{'question':'Students think all eclipses occur because the Moon blocks the Sun. Which explanation best corrects this?','options':['Use a Sun-Earth-Moon model to show that the Moon blocks sunlight during a solar eclipse, while Earth’s shadow falls on the Moon during a lunar eclipse','State that the Moon never blocks sunlight','Explain that eclipses are caused by clouds','Treat solar and lunar eclipses as the same alignment'],'answer_index':0,'explanation':'Solar and lunar eclipses involve different alignments. During a solar eclipse the Moon lies between Earth and the Sun; during a lunar eclipse Earth lies between the Sun and Moon.'},
('B40.json','5005-128'):{'question':'Which cloud type is most directly associated with thunderstorms, lightning, and heavy precipitation?','options':['Cirrus','Cumulus humilis','Nimbostratus','Cumulonimbus'],'answer_index':3,'explanation':'Cumulonimbus clouds grow vertically and are directly associated with thunderstorms, lightning, strong winds, and heavy precipitation. Cirrus clouds may occur during fair weather or precede changing weather, so they are not a reliable fair-weather indicator.'},
('B40.json','5005-131'):{'question':'Which classroom model best represents glacier flow while acknowledging the model’s limitations?','options':['Observe a thick, slow-moving viscous material flowing down a slope and compare it with time-lapse glacier data','Push a rigid tray of ice cubes across a desk','Melt an ice cube rapidly with hot water','Freeze a cup of still water'],'answer_index':0,'explanation':'A viscous material can model slow deformation and flow, while time-lapse data connect the model to real glacier movement. Rigid ice cubes sliding as a block do not represent internal deformation of glacier ice.'},
('B48.json','5005-162'):{'question':'Why do many subduction zones produce volcanic arcs?','options':['Continents melt completely when they collide','Water released from the subducting plate lowers the melting point of rock in the overlying mantle, producing magma','Every volcano is caused by a mantle plume','Ocean water directly turns into magma'],'answer_index':1,'explanation':'As a plate subducts, water and other volatiles are released into the mantle wedge. These lower the rock’s melting temperature, causing partial melting and magma that can rise to form volcanoes.'},
('B59.json','5005-208'):{'question':'Which sequence orders electromagnetic waves from lowest to highest energy?','options':['Gamma → X-ray → ultraviolet → visible → infrared → microwave → radio','Visible → radio → gamma → microwave → ultraviolet → infrared → X-ray','All electromagnetic waves have the same photon energy','Radio → microwave → infrared → visible → ultraviolet → X-ray → gamma'],'answer_index':3,'explanation':'Photon energy increases with frequency. Radio waves have the lowest frequencies in the list, followed by microwaves, infrared, visible, ultraviolet, X-rays, and gamma rays.'},
('B65.json','5005-239'):{'options':['The Moon is larger than the Sun','Tidal effects depend strongly on distance because they arise from differences in gravitational pull across Earth; the nearby Moon therefore has a strong tidal influence','Tides occur only because Earth rotates','The Sun has no gravitational effect on Earth'],'answer_index':1,'explanation':'Tides arise from the gradient in gravitational attraction across Earth. The tidal effect scales approximately with mass divided by distance cubed, so the Moon’s proximity gives it a strong influence despite its smaller mass.'},
('B67.json','5005-249'):{'question':'What is ecological succession?','options':['Change in a community’s species composition over time after disturbance or formation of new habitat','A fixed sequence that always ends in one permanent climax community','The immediate extinction of every species after disturbance','Random change with no influence from environment or species interactions'],'answer_index':0,'explanation':'Ecological succession is change in community composition through colonization, competition, disturbance, and environmental conditions. It does not always follow one fixed path or end in a single permanent climax community.'},
('B67.json','5005-250'):{'options':['List the species in several unrelated habitats','Grow identical plants while changing one resource at a time, using a control and repeated trials, then measure growth','Measure room temperature once','Count animals without changing or measuring a possible limiting resource'],'answer_index':1,'explanation':'A controlled experiment varies one resource while holding other conditions constant and uses replication. Comparing plant growth against a control reveals whether light, water, or nutrients limit growth.'},
('B78.json','5005-278'):{'question':'Students think heavier objects fall faster in the absence of air resistance. Which demonstration best tests the claim?','options':['Drop a feather and coin in an evacuated tube and observe that they fall together','Drop a flat sheet of paper and a book in air without discussing drag','Compare the objects’ weights without dropping them','Use a story about Galileo without collecting evidence'],'answer_index':0,'explanation':'In an evacuated tube, air resistance is removed and objects of different masses accelerate equally under gravity. The feather-and-coin vacuum demonstration should not be conflated with the disputed Leaning Tower story.'},
('B85.json','5005-298'):{'question':'Students ask why solid objects do not pass through one another if atoms contain large regions without nuclei. Which explanation is best?','options':['Electron clouds interact through electromagnetic forces that resist overlap, giving matter its solidity','Atoms are completely solid balls with no internal structure','Gravity alone prevents atoms from overlapping','The empty-space description means ordinary objects should pass through each other'],'answer_index':0,'explanation':'Atomic volume is defined largely by electron clouds, and electromagnetic interactions strongly resist their overlap. Therefore a simplified “mostly empty space” picture does not imply that macroscopic objects can pass through one another.'},
('B87.json','5005-307'):{'options':['They are unrelated processes','Both processes create oxygen without using matter','Some products of one are reactants of the other, so matter cycles while energy flows through the system and eventually dissipates as heat','Both processes consume oxygen in the same way'],'answer_index':2,'explanation':'Photosynthesis stores light energy in chemical bonds and produces glucose and oxygen; respiration uses those materials and releases carbon dioxide and water. Matter can cycle between the processes, but energy flows one way and is eventually released as heat.'},
('B87.json','5005-311'):{'question':'Why can some bacteria use anaerobic respiration in oxygen-poor environments?','options':['Anaerobic respiration always yields more energy than aerobic respiration','All such bacteria are incapable of using oxygen under any condition','They can use terminal electron acceptors such as nitrate or sulfate instead of oxygen','They perform photosynthesis instead of metabolism'],'answer_index':2,'explanation':'In anaerobic respiration, an electron transport chain uses an acceptor other than oxygen, such as nitrate or sulfate. This differs from fermentation, which does not use an external terminal electron acceptor.'},
('B98.json','5005-338'):{'options':['Water provides decorative color to cells','Only plants require water','Water dissolves many ionic and polar substances, supports biochemical reactions, and helps regulate temperature','Water dissolves every known substance'],'answer_index':2,'explanation':'Because water is polar, it is a good solvent for many ionic and polar substances and provides a medium for metabolic reactions. It also helps regulate temperature, but it is not a universal solvent that dissolves everything.'}
}
changes=[]
for p in glob.glob(os.path.join(BD,'B*.json')):
 d=json.load(open(p,encoding='utf-8'));touch=False;name=os.path.basename(p)
 for q in d['questions']:
  spec=fix.get((name,q['id']))
  if spec:
   before={k:q.get(k) for k in spec};q.update(spec);touch=True;changes.append({'file':name,'id':q['id'],'change':'async_reviewer_followup','before':before,'after':spec})
 if touch:
  # batch metadata may need category-independent counts only
  d['count']=len(d['questions']);d['difficulty_target']=dict(__import__('collections').Counter(q['difficulty'] for q in d['questions']));d['type_target']=dict(__import__('collections').Counter(q['type'] for q in d['questions']))
  with open(p,'w',encoding='utf-8') as f:json.dump(d,f,ensure_ascii=False,indent=2)
# rebuild
files=sorted(glob.glob(os.path.join(BD,'B*.json')),key=lambda p:int(os.path.basename(p)[1:-5]));qs=[]
for p in files:qs+=json.load(open(p,encoding='utf-8'))['questions']
outp=os.path.join(ROOT,'assets','questions-full.json');out=json.load(open(outp,encoding='utf-8'));out['questions']=qs;out['question_count']=len(qs);out['subtests']=dict(__import__('collections').Counter(q['subtest'] for q in qs))
with open(outp,'w',encoding='utf-8') as f:json.dump(out,f,ensure_ascii=False,indent=2)
rp=os.path.join(ROOT,'review-fixes.json');r=json.load(open(rp,encoding='utf-8'));r.setdefault('manual_changes',[]).extend(changes);r['async_reviewer_followup_fixes']=len(changes)
with open(rp,'w',encoding='utf-8') as f:json.dump(r,f,ensure_ascii=False,indent=2)
print('fixed',len(changes));print([(x['file'],x['id']) for x in changes])
