#!/usr/bin/env python3
"""Praxis 5001 批量出题调度器

用法:
  python batch_generator.py --batch B1 --category "Reading" --subtest "5002" --count 15
  python batch_generator.py --help

输出:
  E:\Triumph\praxis-5001/assets/batches/B{N}.json
  E:\Triumph\praxis-5001/assets/questions-full.json (自动合并)
"""

import argparse
import json
import os
import sys
from pathlib import Path
from datetime import datetime

# 配置路径
PROJECT_DIR = Path(r"E:\Triumph\praxis-5001")
BATCHES_DIR = PROJECT_DIR / "assets" / "batches"
FULL_FILE = PROJECT_DIR / "assets" / "questions-full.json"

# 确保批次目录存在
BATCHES_DIR.mkdir(parents=True, exist_ok=True)

# 官方蓝图
BLUEPRINT = {
    "5002": {
        "name": "Reading and Language Arts",
        "categories": {
            "Reading": {"current": 14, "target": 57},
            "Writing, Speaking, and Listening": {"current": 16, "target": 63}
        }
    },
    "5003": {
        "name": "Mathematics",
        "categories": {
            "Numbers and Operations": {"current": 8, "target": 28},
            "Algebraic Thinking": {"current": 6, "target": 21},
            "Geometry and Measurement, Data, Statistics, and Probability": {"current": 6, "target": 21}
        }
    },
    "5004": {
        "name": "Social Studies",
        "categories": {
            "United States History, Government, and Citizenship": {"current": 9, "target": 37},
            "Geography, Anthropology, and Sociology": {"current": 6, "target": 25},
            "World History and Economics": {"current": 5, "target": 21}
        }
    },
    "5005": {
        "name": "Science",
        "categories": {
            "Earth Science": {"current": 5, "target": 29},
            "Life Science": {"current": 5, "target": 29},
            "Physical Science": {"current": 6, "target": 29}
        }
    }
}


def load_full_questions():
    """加载现有完整题库，返回问题和最大ID序号"""
    if not FULL_FILE.exists():
        return [], {}
    
    with open(FULL_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    questions = data.get('questions', [])
    max_ids = {}
    for q in questions:
        subtest = q['subtest']
        qid = q['id']
        num = int(qid.split('-')[1])
        if subtest not in max_ids or num > max_ids[subtest]:
            max_ids[subtest] = num
    
    return questions, max_ids


def next_id(subtest, max_ids):
    """获取下一个问题ID"""
    current = max_ids.get(subtest, 0)
    new_num = current + 1
    max_ids[subtest] = new_num
    return f"{subtest}-{new_num:03d}"


def generate_batch_metadata(batch_num, subtest, category, count):
    """生成本批元数据"""
    return {
        "batch": batch_num,
        "generated_at": datetime.now().isoformat(),
        "subtest": subtest,
        "category": category,
        "count": count,
        "difficulty_target": {"easy": 0.2, "medium": 0.5, "hard": 0.3},
        "type_target": {"knowledge": 0.3, "concept": 0.4, "pedagogy": 0.3},
        "blueprint": "official",
        "source_note": "generated by praxis-question-writer"
    }


def merge_and_save(new_questions, max_ids):
    """合并新题目到完整题库并保存"""
    existing, _ = load_full_questions()
    
    # 为新题目分配ID
    for q in new_questions:
        if 'id' not in q or not q['id']:
            q['id'] = next_id(q['subtest'], max_ids)
    
    # 合并
    all_questions = existing + new_questions
    
    # 构建输出
    output = {
        "version": "2.0",
        "exam": "Praxis 5001",
        "exam_name": "Elementary Education: Multiple Subjects",
        "blueprint": "official",
        "blueprint_source": {
            "publisher": "ETS",
            "document": "The Praxis Study Companion: Elementary Education: Multiple Subjects (5001)",
            "url": "https://www.ets.org/content/dam/ets-org/pdfs/praxis/5001.pdf"
        },
        "question_count": len(all_questions),
        "last_updated": datetime.now().isoformat(),
        "statistics": {
            "by_subtest": {},
            "by_category": {},
            "by_difficulty": {},
            "by_type": {}
        },
        "questions": all_questions
    }
    
    # 统计
    for q in all_questions:
        st = q.get('subtest', 'unknown')
        cat = q.get('category', 'unknown')
        diff = q.get('difficulty', 'unknown')
        typ = q.get('type', 'unknown')
        
        output['statistics']['by_subtest'][st] = output['statistics']['by_subtest'].get(st, 0) + 1
        output['statistics']['by_category'][f"{st}-{cat}"] = output['statistics']['by_category'].get(f"{st}-{cat}", 0) + 1
        output['statistics']['by_difficulty'][diff] = output['statistics']['by_difficulty'].get(diff, 0) + 1
        output['statistics']['by_type'][typ] = output['statistics']['by_type'].get(typ, 0) + 1
    
    # 保存
    with open(FULL_FILE, 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    
    return output


def validate_question(q, qid):
    """验证单题必填字段"""
    required = ['id', 'subtest', 'category', 'difficulty', 'type', 'question', 'options', 'answer_index', 'explanation', 'source']
    missing = [f for f in required if f not in q]
    if missing:
        return False, f"Missing fields: {missing}"
    
    if q['answer_index'] < 0 or q['answer_index'] >= len(q['options']):
        return False, f"Invalid answer_index {q['answer_index']} for {len(q['options'])} options"
    
    if len(q['options']) != 4:
        return False, f"Expected 4 options, got {len(q['options'])}"
    
    return True, "OK"


def main():
    parser = argparse.ArgumentParser(description='Praxis 5001 批量出题')
    parser.add_argument('--batch', '-b', required=True, help='批次号 (如 B1)')
    parser.add_argument('--subtest', '-s', required=True, help='科目代码 (5002/5003/5004/5005)')
    parser.add_argument('--category', '-c', required=True, help='类别名称')
    parser.add_argument('--count', '-n', type=int, default=10, help='题目数量 (默认10)')
    parser.add_argument('--output', '-o', help='输出文件路径')
    
    args = parser.parse_args()
    
    # 验证科目
    if args.subtest not in BLUEPRINT:
        print(f"错误: 未知科目 {args.subtest}")
        sys.exit(1)
    
    # 验证类别
    valid_categories = list(BLUEPRINT[args.subtest]['categories'].keys())
    if args.category not in valid_categories:
        print(f"错误: 未知类别 '{args.category}'")
        print(f"有效类别: {', '.join(valid_categories)}")
        sys.exit(1)
    
    print(f"批次 {args.batch}")
    print(f"科目: {args.subtest} - {BLUEPRINT[args.subtest]['name']}")
    print(f"类别: {args.category}")
    print(f"数量: {args.count}")
    print()
    print("现在请用 praxis-question-writer 技能生成题目...")
    print(f"提示词: 生成 {args.count} 道 {args.subtest} 的 '{args.category}' 类别题目，")
    print(f"难度分布 easy:{int(args.count*0.2)} medium:{int(args.count*0.5)} hard:{int(args.count*0.3)}")
    print(f"题型分布 knowledge:{int(args.count*0.3)} concept:{int(args.count*0.4)} pedagogy:{int(args.count*0.3)}")
    print(f"输出格式为 JSON，保存到 {args.output or '手动保存'}")
    print()
    print("=" * 60)


if __name__ == '__main__':
    main()
