import { build } from 'esbuild';

await build({
  entryPoints: ['worker-src/worker.mjs'],
  bundle: true,
  format: 'esm',
  target: 'es2022',
  platform: 'browser',
  outfile: 'site/_worker.js',
  banner: {
    js: '// Generated by build-worker.mjs from worker-src/*.mjs — do not edit site/_worker.js by hand.',
  },
  logLevel: 'info',
});
